baseURL = 'https://msilvestrini92.github.io/blog/'
languageCode = 'en-us'
title = "Mattia Silvestrini's Blog"
theme = "m10c"

[params]
  author = "Mattia Silvestrini"
  description = "A blog about all things technical, plus some physics"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/msilvestrini92"

  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/mattia-silvestrini-4b8943114/"
